### PR TITLE
Bugfix: improve Cosmos DB statement parser

### LINKED ISSUE #1002: CosmosDB: Run SQL from Criteria
# Bug Report

## Describe the Bug

It's possible to write SQL statement snippets in a `Criterion` and run them in Cosmos DB. For example to select everything use this `Criterion`:

```java
new Criterion("foo", "IN", "(1) OR 1=1 ")
```

The SQL snippet is inserted in a statement after the `WHERE` clause.

### Expected Behavior

SQL in a `Criterion` should be executed by CosmosDB queries.

### Observed Behavior

It's possible to write SQL in a `Criterion` at it's run from CosmosDB.

## Steps to Reproduce

Unit Test to reproduce
```java

    @Test
    void test_method() {

       /* Prepare CosmosDB with two assets */

        QuerySpec querySpec = QuerySpec.Builder.newInstance()
                .filter(
                        List.of(new Criterion("foo", "IN", "(1) OR 1=1 ")) // SELECT ALL
                )
                .build();
 
        List<Asset> assets = assetIndex.queryAssets(querySpec).collect(Collectors.toList());

        assertThat(assets).hasSize(2);
    }
}

```

## Context Information

At the time of writing this is difficult to abuse, as it's not possible to query a connector with a public API. Additionally CosmosDB only supports `SELECT` statements, so it won't be possible to execute `DROP` or `DELETE` statements.

As the query-code is in a library all queryable CosmosDB extensions should be affected.

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### LINKED ISSUE #1282: Bugfix: let Cosmos handle `IN` expressions properly
# Bug Report

## Describe the Bug
Currently Cosmos requires that `IN` expressions are formulated in a particular way, i.e. `key IN ('value1', 'value2')` which is very error prone and is vulnerable to SQL injection.

### Expected Behavior
Interpret the right-hand operand and use prepared statements.

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

Properly interprets the SQL-statements based on the right-hand operand of the `Criterion` and adds statement placeholders as needed.

## Why it does that

To make the statement interpreter more robust and avoid SQL injection attacks.

## Linked Issue(s)

Closes #1282 
Closes #1002 

## Checklist

- [x] added appropriate tests?
- [ ] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Comment by paullatzelsperger** [comment]
closing this because #1283 is already there.

File: extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/WhereClause.java [hunk 1]
```diff
@@ -70,32 +70,17 @@ String getWhere() {
...
-                throw new IllegalArgumentException("Cannot build SqlParameter for operator: " + operator);
-        }
-    }
 
-    private String sanitizedParameterName(String operandLeft) {
-        return "@" + operandLeft.replaceAll("\\.", "");
+        var operandLeft = sanitize(criterion.getOperandLeft().toString());
+        where += where.startsWith("WHERE") ? " AND" : "WHERE"; //if we have a chained WHERE ... AND ... statement
+        parameters.addAll(expr.toParameters());
+        where += String.format(" %s.%s %s %s", objectPrefix, operandLeft, criterion.getOperator(), expr.toValuePlaceholder());
```
Comment (ndr-brt) [inline extensions/azure/cosmos/cosmos-common/src/main/java/org/eclipse/dataspaceconnector/azure/cosmos/dialect/WhereClause.java:83]: The knowledge on how to format a condition should stay in the `CosmonConditionExpression` class, then the `WhereClause` could only get the list of conditions, transforming them to string and joining with the ` AND ` separator and `WHERE ` prefix.

**Review by ndr-brt — APPROVED** [review]
