### PR TITLE
Bugfix: replace countdown latches with awaitility

### LINKED ISSUE #1505: ContractNegotiationIntegrationTest: race condition
# Bug Report

## Describe the Bug

Observed in a non-reproducible manner
```
ContractNegotiationIntegrationTest > testNegotiation_initialOfferAccepted() FAILED
 org.opentest4j.AssertionFailedError:
 expected: null
  but was: org.eclipse.dataspaceconnector.spi.types.domain.contract.agreement.ContractAgreement@e70b6dd7
     at java.base@11.0.15/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     at java.base@11.0.15/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     at java.base@11.0.15/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at app//org.eclipse.dataspaceconnector.contract.negotiation.ContractNegotiationIntegrationTest.testNegotiation_initialOfferAccepted(ContractNegotiationIntegrationTest.java:78
```

## Possible Implementation

Latch waits for the observable to be triggered, then test makes assertion on persisted data.

This is a race condition, since data is persisted after the observable is invoked.

Add post* observable operations?

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

Fixes a race condition in the `ContractNegotiationIntegrationTest` by replacing the `CountdownLatch` with `awaitility`.
Awaitility allows for better control over timed assertions than a latch - here it allows us to assert multiple things, in particular:
- the listener's `pre*` method has been called
- both negotiation managers are in the desired state

The latch only waited for the _first_ condition, whereas Awaitility waits for _all of them_.

## Why it does that

To avoid race conditions, causing sporadically failing tests.

## Further notes
- countdown latches have been replaced only in the `ContractNegotiationIntegrationTest`
- replacing was also done in the `@Disabled` tests (why are they disabled?)

## Linked Issue(s)

Closes #1505 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java [hunk 1]
```diff
@@ -23,29 +25,36 @@
...
+import static org.mockito.Mockito.mock;
+import static org.mockito.Mockito.times;
 import static org.mockito.Mockito.verify;
 import static org.mockito.Mockito.when;
 
 @ComponentTest
 class ContractNegotiationIntegrationTest extends AbstractContractNegotiationIntegrationTest {
 
+    private static final Duration DEFAULT_TEST_TIMEOUT = Duration.ofSeconds(15);
+    private static final Duration DEFAULT_POLL_INTERVAL = Duration.ofSeconds(1);
```
Comment (algattik) [inline core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java:44]: nit: no need for such a "long" interval I think, they add up between tests, so something like 0.1s should do

File: core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java [hunk 2]
```diff
@@ -60,40 +69,47 @@ void testNegotiation_initialOfferAccepted() throws Exception {
...
+                .untilAsserted(() -> {
+                    var consumerNegotiation = consumerStore.find(consumerNegotiationId);
+                    var providerNegotiation = providerStore.findForCorrelationId(consumerNegotiationId);
+
+                    // Assert that provider and consumer have the same offers and agreement stored
+                    assertThat(consumerNegotiation).isNotNull();
+                    assertThat(providerNegotiation).isNotNull();
+                    assertThat(consumerNegotiation.getState()).isEqualTo(CONFIRMED.code());
+                    assertThat(consumerNegotiation.getContractOffers()).hasSize(1);
+                    assertThat(consumerNegotiation.getContractOffers().size()).isEqualTo(providerNegotiation.getContractOffers().size());
```
Comment (algattik) [inline core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java:84]: seems strange given previous line. Is it meant to revert the assertion?

File: core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java [hunk 3]
```diff
@@ -60,40 +69,47 @@ void testNegotiation_initialOfferAccepted() throws Exception {
...
+                    assertThat(consumerNegotiation.getLastContractOffer()).isEqualTo(providerNegotiation.getLastContractOffer());
+                    assertThat(consumerNegotiation.getContractAgreement()).isNotNull();
```
Comment (algattik) [inline core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java:86]:
```suggestion
```
redundant with subsequent line

File: core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java [hunk 4]
```diff
@@ -157,24 +178,28 @@ void testNegotiation_agreementDeclined() throws Exception {
...
-        verify(validationService, Mockito.atLeastOnce()).validate(token, offer);
-        verify(validationService, Mockito.atLeastOnce()).validate(eq(token), any(ContractAgreement.class), any(ContractOffer.class));
+        await().atMost(DEFAULT_TEST_TIMEOUT)
+                .pollInterval(DEFAULT_POLL_INTERVAL)
+                .untilAsserted(() -> {
+                    var consumerNegotiation = consumerStore.find(consumerNegotiationId);
+                    var providerNegotiation = providerStore.findForCorrelationId(consumerNegotiationId);
+
+                    // Assert that provider and consumer have the same offers stored
+                    assertThat(consumerNegotiation).isNotNull();
```
Comment (algattik) [inline core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java:188]: seems much duplicate code?

File: core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java (hunk 2 above)
Comment (paullatzelsperger) [reply core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java:84]: I don't really know, but I would assume that both things are to be verified, the size being equal to 1, and the sizes of both contract offer lists being equal

File: core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java (hunk 4 above)
Comment (paullatzelsperger) [reply core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java]: i extracted a method that performs some basic assertions, but I'm not sure whether that makes the code _more_ or _less_ readable.

File: core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java (hunk 2 above)
Comment (algattik) [reply core/contract/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/ContractNegotiationIntegrationTest.java]: ok to resolve

**Review by algattik — APPROVED** [review]
