### PR TITLE
Integration tests: Run CosmosDB integration tests on cloud in CI

### LINKED ISSUE #845: CosmosDB Emulator failed to reach running state
# Bug Report

## Describe the Bug
During CosmosDb-Integration tests the emulator fails to reach the "running" state within 1200 seconds

### Expected Behavior
it reaches the "running" state

### Observed Behavior
[see this CI run](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/5460040988?check_suite_focus=true)

## Steps To Reproduce
not reproducible, seems to happen randomly

## Context Information
n/a

## Detailed Description
n/a

### PR DESCRIPTION
**Pull request by algattik**
## What this PR changes/adds

Run Cosmos DB tests on a cloud instance in CI, instead of emulator.

As a result PRs from forks are not automatically tested in CI. Contributors should run CI on their fork, and post a link to the successful build in the PR.

Successful run: https://github.com/agera-edc/DataSpaceConnector/actions/runs/2038470930

## Why it does that

Emulator is not reliable running in GitHub agent.

## Further notes

Adapted one unit test for portability, since deleteAllItemsByPartitionKey is disabled by default on new Cosmos DB accounts.

## Linked Issue(s)

Closes #845 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java [hunk 1]
```diff
@@ -89,7 +88,11 @@ void setUp() {
 
     @AfterEach
     void tearDown() {
-        container.deleteAllItemsByPartitionKey(new PartitionKey(TEST_PARTITION_KEY), new CosmosItemRequestOptions());
+        // Delete items one by one as deleteAllItemsByPartitionKey is disabled by default on new Cosmos DB accounts.
+        PartitionKey partitionKey = new PartitionKey(TEST_PARTITION_KEY);
+        container.readAllItems(partitionKey, CosmosDbEntity.class)
```
Comment (paullatzelsperger) [inline extensions/azure/cosmos/assetindex-cosmos/src/test/java/org/eclipse/dataspaceconnector/assetindex/azure/CosmosAssetIndexIntegrationTest.java:93]: could have just used `AssetDocument.class`

**Review by paullatzelsperger — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]
