### PR TITLE
DataManagementApi: In-memory policy store implementation

### LINKED ISSUE #803: Create `PolicyStore` and default impl
A `PolicyStore` interface must be implemented with the following API:
```java
public interface PolicyStore {
    // returns null if not found
    Policy findById(String policyId);
    Stream<Policy> findAll(QuerySpec spec);
    void save(Policy policy);
    // returns null if not found, returns the deleted item otherwise.
    Policy delete(String policyId);
}
```
If any exception occurs, a `EdcPersistenceException` should be thrown.

In addition, an in-memory implementation should be provided.

### PR DESCRIPTION
**Pull request by Izzzu**
## What this PR changes/adds

- Add PolicyStore interface.
- Implement in memory version of PolicyStore.
- Add InMemoryPolicyStoreExtension

## Why it does that

Implementation of PolicyStore according to definitions in upstream issue: [#803](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/803)

## Further notes

This PR covers also following points:

- Extracting common code from store implementations of findAll(QuerySpec spec) methods into a class ReflectionBasedQueryResolver.
- Removing not up to date javadoc from CosmosContractDefinitionStore for Stream<ContractDefinition> findAll(QuerySpec spec) method
- Adding test in CosmosContractNegotiationStoreIntegrationTest verifying that filtering by non existent sort field returns empty stream.
- Change in InMemoryContractNegotiationStore to be consistent with other stores to return empty stream in case of filtering by nonexistent sort field.

## Linked Issue(s)

Closes #803 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java [hunk 1]
```diff
@@ -0,0 +1,85 @@
...
+import java.util.stream.Stream;
+
+import static org.eclipse.dataspaceconnector.common.reflection.ReflectionUtil.propertyComparator;
+
+/**
+ * Applies query on a stream. Uses reflection to fetch object fields. Used in stores implementations.
+ *
+ * @param <T> type of the stream elements.
+ */
+public class ReflectionBasedQueryResolver<T> extends QueryResolver<T> {
```
Comment (paullatzelsperger) [inline spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java:28]: Can we move this into `:core:core-base`? it would then have to be passed into constructors in the `*Stores`

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryResolver.java [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+package org.eclipse.dataspaceconnector.spi.query;
+
+import java.util.stream.Stream;
+
+/**
+ * Class responsible for applying queries on an input elements of type T. Currently supports querying a stream of elements.
+ *
+ * @param <T> type of the queried elements.
+ */
+public abstract class QueryResolver<T> {
```
Comment (paullatzelsperger) [inline spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryResolver.java:23]: could this be an interface, even a `@FunctionalInterface`?

File: spi/core-spi/build.gradle.kts [hunk 3]
```diff
@@ -30,6 +30,7 @@ dependencies {
 
     implementation("io.opentelemetry:opentelemetry-api:${openTelemetryVersion}")
 
+    api(project(":common:util"))
```
Comment (paullatzelsperger) [inline spi/core-spi/build.gradle.kts:33]: unless you're exposing classes from `:common:util` in this module's public API, it's better to use `implementation` dependencies

File: extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java [hunk 4]
```diff
@@ -61,40 +62,17 @@ public CosmosContractDefinitionStore(CosmosDbApi cosmosDbApi, TypeManager typeMa
         this.retryPolicy = retryPolicy;
         this.partitionKey = partitionKey;
         lockManager = new LockManager(new ReentrantReadWriteLock(true));
+        queryResolver = new ReflectionBasedQueryResolver<>(ContractDefinition.class);
```
Comment (paullatzelsperger) [inline extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java:65]: this should get passed in through the CTor, so that the `ReflectionBasedQueryResolver` can be moved to core

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]

File: spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java [hunk 5]
```diff
@@ -0,0 +1,64 @@
...
+import org.eclipse.dataspaceconnector.spi.persistence.EdcPersistenceException;
+import org.eclipse.dataspaceconnector.spi.query.QuerySpec;
+import org.jetbrains.annotations.Nullable;
+
+import java.util.stream.Stream;
+
+/**
+ * Persists {@link Policy}.
+ */
+public interface PolicyStore {
```
Comment (paullatzelsperger) [inline spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java:26]: I think this should be in `contract-spi`. We might need access to it in runtimes that don't need the contract stuff.

File: spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java [hunk 6]
```diff
@@ -0,0 +1,64 @@
...
+ *  terms of the Apache License, Version 2.0 which is available at
+ *  https://www.apache.org/licenses/LICENSE-2.0
+ *
+ *  SPDX-License-Identifier: Apache-2.0
+ *
+ *  Contributors:
+ *       Microsoft Corporation - initial API and implementation
+ *
+ */
+package org.eclipse.dataspaceconnector.spi.contract.policy.store;
```
Comment (ndr-brt) [inline spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java:14]: Since the `Policy` class is in the `core-spi`, maybe also this store will fit better there? Maybe could be time for a `policy-spi` module?

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+        // filter
+        Stream<Predicate<T>> predicateStream = spec.getFilterExpression().stream().map(this::toPredicate);
+        var andPredicate = predicateStream.reduce(x -> true, Predicate::and);
+        Stream<T> filteredStream  = stream.filter(andPredicate);
+
+        // sort
+        var sortField = spec.getSortField();
+
+        if (sortField != null) {
+            // if the sort field doesn't exist on the object -> return empty
```
Comment (ndr-brt) [inline spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java:63]: This behaviour is kinda strange, I would prefer an error if the sort field does not exist, it's pretty common on query systems (like sql databases), otherwise it will be pretty hard to understand why the query returned an empty stream.

File: spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java (hunk 5 above)
Comment (ndr-brt) [reply spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java:26]: did you mean `:spi:policy-spi`?

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java [hunk 8]
```diff
@@ -0,0 +1,85 @@
...
+
+import org.eclipse.dataspaceconnector.common.reflection.ReflectionUtil;
+
+import java.util.function.Predicate;
+import java.util.stream.Stream;
+
+import static org.eclipse.dataspaceconnector.common.reflection.ReflectionUtil.propertyComparator;
+
+/**
+ * Applies query on a stream. Uses reflection to fetch object fields. Used in stores implementations.
```
Comment (paullatzelsperger) [inline spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java:24]: could you also add a note that this is the default implementation?

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java (hunk 7 above)
Comment (Izzzu) [reply spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java:63]: Agree, but this code was extracted directly from query methods in *Store classes as a refactoring, not changed. I wouldn't increase the scope of this PR to change this logic, as it would impact several store implementations.

File: spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java (hunk 5 above)
Comment (Izzzu) [reply spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java]: Makes sense, I must have left it in this module by mistake. I created :spi:policy-spi module. Thanks

File: spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java (hunk 6 above)
Comment (Izzzu) [reply spi/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/contract/policy/store/PolicyStore.java]: I created policy-spi in spi and moved the PolicyStore there to be consistent with other store interfaces

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java (hunk 8 above)
Comment (Izzzu) [reply spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/ReflectionBasedQueryResolver.java]: Done. Changed to 
> Default implementation of {@link QueryResolver} that applies query on a stream. Uses reflection to fetch object fields. Used in stores implementations.

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryResolver.java (hunk 2 above)
Comment (Izzzu) [reply spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryResolver.java]: fully agree, changed

File: extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java (hunk 4 above)
Comment (Izzzu) [reply extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java:65]: I think it's related to your previous comment: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/930#discussion_r833382897
Why we should move it to core-base? Are modules allowed to depend on core-base?

Comment (paullatzelsperger) [reply extensions/azure/cosmos/contract-definition-store-cosmos/src/main/java/org/eclipse/dataspaceconnector/contract/definition/store/CosmosContractDefinitionStore.java:65]: what I meant was to _pass this as constructor argument_ rather than _instantiating directly_. That way, the `CosmosContractDefinitionStore` only has a dependency on `QueryResolve`.
Then, the `ReflectionBasedQueryResolver` instance could be `@Inject`-ed in the `CosmosContractDefinitionStoreExtension`. This would of course require some extension to have registered it previously. 

The more I think about this, the more I think the way it is now is actually better, because is much less hassle and it hides the implementation. So please feel free to disregard :)

**Review by paullatzelsperger — COMMENTED** [review]
LGTM once checkstyle violations are resolved.

**Review by paullatzelsperger — APPROVED** [review]

**Review by jimmarino — APPROVED** [review]

**Comment by jimmarino** [comment]
@Izzzu can you fix the conflicts and I'll merge?

**Comment by Izzzu** [comment]
> @Izzzu can you fix the conflicts and I'll merge?

@jimmarino done, thanks!
