### PR TITLE
fix: use the `range` to limit offers, not definitions

### LINKED ISSUE #2008: Potential bug: paging is not applied correctly during a catalog request
# Bug Report

## Describe the Bug
There could be a bug in the `ContractOfferServiceImpl`, where the `Range` parameter (i.e. the paging) is applied incorrectly

### Expected Behavior
Paging should limit the number of assets (or rather: `ContractOffers`) that are returned.

### Observed Behavior
The current implementation looks like this:
```java
    @Override
    @NotNull
    public Stream<ContractOffer> queryContractOffers(ContractOfferQuery query, Range range) {
        var agent = agentService.createFor(query.getClaimToken());

        return definitionService.definitionsFor(agent, range) //<-- this might be incorrect
                .flatMap(definition -> {
                    var assets = assetIndex.queryAssets(definition.getSelectorExpression());
                    return Optional.of(definition.getContractPolicyId())
                            .map(policyStore::findById)
                            .map(policy -> assets.map(asset -> createContractOffer(definition, policy.getPolicy(), asset)))
                            .orElseGet(Stream::empty);
                });
    }
```

which indicates that the `Range` limits the stream coming from `definitionsFor()` rather than the `assets` variable.

_Note: this is a suspicion at this point, and needs to be investigated_

## Possible Implementation
Apply the `Range` parameter to the resulting `Stream<ContractOffer>`

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

In the current implementation of the `ContractOfferSerivceImpl`, the `Range` parameter is used to limit `ContractDefinitions` rather than the resulting `ContractOffers`. This is a bug and could lead to more contractOffers than specified by `Range`.

This PR dynamically composes the `Stream<Asset>` based on the `from` and `to` parameters of the `Range`, skipping as many `Assets` as necessary, and applying the `skip` and `limit` parameters to the respective database query.

In doing that, it was necessary to add a method `AssetIndex.count(QuerySpec)` to obtain the number of Assets referenced by a particular `AssetSelectorExpression`.

## Why it does that

To guarantee the correct/expected behaviour of the paging.

## Further notes

- This solution works regardless of the underlying implementation of the Stream returned by the AssetIndex
- There are other pending changes to be made (#2015 and #2009) which will also influence this area of code. 

Closes #2008 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [x] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java [hunk 1]
```diff
@@ -55,15 +57,21 @@ public ContractOfferServiceImpl(ParticipantAgentService agentService, ContractDe
     @NotNull
     public Stream<ContractOffer> queryContractOffers(ContractOfferQuery query, Range range) {
         var agent = agentService.createFor(query.getClaimToken());
-
-        return definitionService.definitionsFor(agent, range)
+        var offers = definitionService.definitionsFor(agent)
```
Comment (ndr-brt) [inline core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java:60]: I know that there aren't many ways to do this, but could this lead to long-blocked threads? 
I mean, for every page we have to fetch all the definitions - that could be not a big issue, also in the case if there are a lot of them, since they are really little.
But, on the last page request here the service will fetch all the definitions, query/evaluate all the policies, fetch all the assets, and then `skip` and `limit` are applied, as they are located after a `flatMap`, so the time needed to fetch the last page is actually the same time needed to fetch all the catalog in a single call.

e.g. (speculative) having 100.000 (pretty standard value) definitions means that there will be 200.000 queries to the policy store (access and contract) and 100.000 to the asset index. let's assume that the stores are really fast and the policy evaluation take no-time, if we count 1ms for every definition the single page request could take a time around 1 minute.

I don't remember if the issue with the "full catalog" fetch was with this operation of with serdes/transmission, but I think this implementation could lead poor performances and potentially to OOM exceptions.

File: core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java [hunk 2]
```diff
@@ -55,15 +57,21 @@ public ContractOfferServiceImpl(ParticipantAgentService agentService, ContractDe
...
-                            .map(policy -> assets.map(asset -> createContractOffer(definition, policy.getPolicy(), asset)))
+                            .map(policy -> assetIndex.queryAssets(spec).map(asset -> createContractOffer(definition, policy.getPolicy(), asset)))
                             .orElseGet(Stream::empty);
-                });
+                })
+                // todo: change this: take limit/offset from query
+                .skip(range.getFrom())
+                .limit(range.getTo() - range.getFrom())
+                .collect(Collectors.toList());
+        return offers.stream();
```
Comment (ndr-brt) [inline core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java:73]: I would avoid to collect and stream again

**Review by ndr-brt — COMMENTED** [review]
I'm worried about the performances implications of this

File: core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java (hunk 2 above)
Comment (paullatzelsperger) [reply core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java:73]: yeah, i had that for debugging. should be removed.

File: core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java (hunk 1 above)
Comment (paullatzelsperger) [reply core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java:60]: >... skip and limit are applied, as they are located after a flatMap
well, from a logical standpoint, that is the only place where `skip` and `limit` _can_ be applied, because we need the flat list of assets/offers first. 
Maybe we could collect first all the `Assets`, slice out the page and _then_ convert them into offers? That would still rely on the store not materializing the stream prematurely, but would save calls to the `PolicyDefinitionStore`.

Also, the way the `range` was applied before, was flat-out wrong, because it limited the number of `contractDefinitions`, so _some_ action needed to be taken.

The problem with the full list was that jetty ran into timeouts (and potentially body-size limits) when using anything other than in-mem.

> I mean, for every page we have to fetch all the definitions ...
We could add a cache for the definitions and policies (see #1173), if that needs to be optimized.

Comment (paullatzelsperger) [reply core/control-plane/contract/src/main/java/org/eclipse/dataspaceconnector/contract/offer/ContractOfferServiceImpl.java]: The implementation was updated in commit https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/2018/commits/ea755913749a7e98e5c82891cd951fc46e8e7a25, as was the PR descriptions

**Review by ndr-brt — APPROVED** [review]
I think this is probably the most efficient way to do this at the moment.
The next thing where we could investigate is actually supporting streaming in the `SqlExecutor` (because now we are reading everything in a list in memory on which the stream is opened).
Will open an issue about.

**Review by wolf4ood — APPROVED** [review]

**Review by juliapampus — APPROVED** [review]
