### PR TITLE
fix: remove logging of api key from TokenBasedAuthenticationExtension

### LINKED ISSUE #1780: Security: TokenBasedAuthenticationExtension logs API Key on start-up
# Bug Report

## Describe the Bug

The TokenBasedAuthenticationExtension logs the API Key on start-up. It's best practice to keep sensitive data out of the logs. Hence I would suggest to remove this log line.

Example Logs:
``` 
[2022-08-04 06:42:12] [INFO   ] Initialized Core Contract Service
[2022-08-04 06:42:12] [INFO   ] Initialized Core Transfer
[2022-08-04 06:42:12] [INFO   ] API Authentication: using static API Key 'password'
[2022-08-04 06:42:12] [INFO   ] Initialized org.eclipse.dataspaceconnector.api.auth.TokenBasedAuthenticationExtension
[2022-08-04 06:42:12] [INFO   ] Initialized API Core
```

### Expected Behavior
- Passwords not part of the log file

### Observed Behavior
- Password is loggged

## Steps to Reproduce
1. Start EDC with TokenBasedAuthenticationExtension
2. Check logs

## Context Information

- Used version: Milestone 5

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by juliapampus**
## What this PR changes/adds

Removes plain key from log line.

## Why it does that

Password shouldn't be part of the log file

## Further notes

--

## Linked Issue(s)

Closes #1780

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: extensions/api/auth-tokenbased/src/main/java/org/eclipse/dataspaceconnector/api/auth/TokenBasedAuthenticationExtension.java [hunk 1]
```diff
@@ -56,7 +55,7 @@ public void initialize(ServiceExtensionContext context) {
             apiKey = context.getSetting(AUTH_SETTING_APIKEY, UUID.randomUUID().toString());
         }
 
-        context.getMonitor().info(format("API Authentication: using static API Key '%s'", apiKey));
+        context.getMonitor().info("API Authentication: using static API Key");
```
Comment (ndr-brt) [inline extensions/api/auth-tokenbased/src/main/java/org/eclipse/dataspaceconnector/api/auth/TokenBasedAuthenticationExtension.java:58]: I would just override the `name()` method making it return like "Static token API Authentication"

**Review by ndr-brt — APPROVED** [review]
