### PR TITLE
bugfix: avoid endless loops on contract negotiation sending failure

### LINKED ISSUE #1487: core: if negotiation sending fails start loops endlessly
# Bug Report

## Describe the Bug
If for any reason the provider connector respond with an error to the negotiation sending, the consumer will start try to send it again endlessly

### Expected Behavior
There should be a limit of retries, after which the contract should transit to ERROR.

### Observed Behavior
In the `ContractNegotiationManager`s instances there is no retry handling 

## Steps to Reproduce
-

## Context Information
-

## Detailed Description
-

## Possible Implementation
A `SendRetryManager` should be introduced and consulted after every sending failure, if the number of retries exceeds the limit, the negotiation will transit to `ERROR` (as done in the `TransferProcessManagerImpl`)

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Avoid endless loops on contract negotiation sending failures.

## Why it does that

To avoid log flooding.

## Further notes

- used the `SendRetryManager` component, generalized to work also with negotiations and moved to the `state-machine-lib` module
- introduced `Entity` interface, that could be a starting point for #1463 (used an interface because it was the easiest thing to do, probably a class would fit better)
- introduced an internal contract negotiation manager component called `AsyncSendResultHandler` that takes care of handling the async results, this was to remove a lot of duplication, and actually makes the code more readable.
- I really think the `SendRetryManager` is pretty trivial to understand, I have in mind a refactor that could make everything more understandable, will propose it in another PR as this brought already enough modifications.

## Linked Issue(s)

Closes #1487 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Review by ronjaquensel — APPROVED** [review]

File: core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationManager.java [hunk 1]
```diff
@@ -136,10 +160,68 @@ public T build() {
...
+            return this;
+        }
+
+        public AsyncSendResultHandler onFailure(Consumer<ContractNegotiation> onFailureHandler) {
+            this.onFailureHandler = onFailureHandler;
+            return this;
+        }
+
+        public BiConsumer<Object, Throwable> build() {
+            return (response, throwable) -> {
```
Comment (paullatzelsperger) [inline core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/AbstractContractNegotiationManager.java:201]: `onFailureHandler` and `onSuccessHandler` both can be `null` here. Either defensively add a null-check to the `if`-statements in L209 and L218, or add non-null requirements in the `build` method.
As a third option, both handlers could have default noop consumers.

File: core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java [hunk 2]
```diff
@@ -246,6 +244,11 @@ public void enqueueCommand(ContractNegotiationCommand command) {
         commandQueue.enqueue(command);
     }
 
+    @Override
+    protected String getName() {
+        return "Consumer";
```
Comment (paullatzelsperger) [inline core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ConsumerContractNegotiationManagerImpl.java:249]: nit: could be a constant

File: core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java [hunk 3]
```diff
@@ -196,6 +193,11 @@ public StatusResult<ContractNegotiation> consumerApproved(ClaimToken token, Stri
         return StatusResult.success(negotiation);
     }
 
+    @Override
+    protected String getName() {
+        return "Provider";
```
Comment (paullatzelsperger) [inline core/contract/src/main/java/org/eclipse/dataspaceconnector/contract/negotiation/ProviderContractNegotiationManagerImpl.java:198]: nit: could be a constant

**Review by paullatzelsperger — APPROVED** [review]
