### PR TITLE
fix: IDS date serialization

### LINKED ISSUE #1226: IDS: error when (de)serializing dates
# Bug Report

## Describe the Bug
Dates cannot be (de)serialized correctly when mapping IDS objects to/from JSON. This leads to missing dates in contract agreements on consumer side, as the information is lost during mapping.

### Expected Behavior
A contract agreement has the same dates on provider and consumer side.

### Observed Behavior
Contract agreements on consumer side have empty/zero date values.

## Context Information
When the `ObjectMapper` serializes just an `XMLGregorianCalendar`, the resulting string has the correct format (timezone specified like `+02:00`) and can be deserialized correctly. But when using the same `ObjectMapper` to deserialize a `ContractAgreement` containing `XMLGregorianCalendar` instances, the resulting string contains the timezone in the format `UTC`, which leads to errors during deserialization. 

The IDS serializer is capable of correctly (de)serializing the dates in IDS objects. Its integration will therefore solve this issue. But until the serializer is integrated, there should be a workaround that works with the standard `ObjectMapper`.

## Possible Implementation
The problem can be solved by using custom (de)serializers for objects of type `XMLGregorianCalendar`.

### PR DESCRIPTION
**Pull request by ronjaquensel**
## What this PR changes/adds

It add a custom serializer and deserializer to the `ObjectMappers` in the `ids` modules.

## Why it does that

Enables serialization and deserialization of `XMLGregorianCalendar` instances. Thus, the dates in `ContractAgreements` can be mapped correctly.

## Further notes

Once the IDS Information Model serializer is integrated, this solution should be deprecated.

## Linked Issue(s)

Closes #1226 

## Checklist

- [X] added appropriate tests?
- [ ] performed checkstyle check locally?
- [X] added/updated copyright headers?
- [X] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [X] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [X] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Review by DominikPinsel — APPROVED** [review]

File: data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java [hunk 1]
```diff
@@ -147,6 +148,7 @@ private void registerControllers(ServiceExtensionContext serviceExtensionContext
         objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
         objectMapper.configure(DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY, true);
         objectMapper.registerSubtypes(IdsConstraintImpl.class);
+        objectMapper.registerModule(new XmlGregorianCalendarModule());
```
Comment (ndr-brt) [inline data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java:151]: I see this `objectMapper` definition nearly equal to the one in `IdsMultipartDispatcherServiceExtension` and in `AbstractMultipartDispatcherIntegrationTest`. Could be extracted in an `ObjectMapperFactory` in the `ids-core` module.

**Review by ndr-brt — APPROVED** [review]
Great! This will enable #1127

File: data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java (hunk 1 above)
Comment (ronjaquensel) [reply data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java:151]: Good point, I'll add an `ObjectMapperFactory`, will make the extensions a little cleaner.

Comment (ronjaquensel) [reply data-protocols/ids/ids-api-multipart-endpoint-v1/src/main/java/org/eclipse/dataspaceconnector/ids/api/multipart/IdsMultipartApiServiceExtension.java:151]: Good point, I'll add an `ObjectMapperFactory`, will make the extensions a little cleaner.

**Review by bscholtes1A — APPROVED** [review]
