### PR TITLE
Bugfix: fixed more Cosmos DB tests

### LINKED ISSUE #1313: Broken Cosmos DB integration tests
# Bug Report

## Describe the Bug 
Cosmos DB CI tests are broken on `main`

https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/runs/6454242008?check_suite_focus=true

```
CosmosAssetIndexIntegrationTest > findAll_withInvalidFilter_throwsException() FAILED
    Expecting message to be:
      "Cannot build SqlParameter for operator: STARTSWITH"
    but was:
      "Cannot build WHERE clause, reason: unsupported operator STARTSWITH"


CosmosAssetIndexIntegrationTest > queryAssets_operatorIn_notFound() FAILED
Syntax error, incorrect syntax near '@asset_prop_id'

CosmosAssetIndexIntegrationTest > queryAssets_operatorIn() FAILED
Syntax error, incorrect syntax near '@asset_prop_id'

CosmosAssetIndexIntegrationTest > queryAssets_operatorIn_noUpTicks() FAILED
Syntax error, incorrect syntax near '@asset_prop_id'

CosmosAssetIndexIntegrationTest > findAll_withFilteringOperatorIn_limitExceedsResultSize() FAILED
Syntax error, incorrect syntax near '@foo'.
```

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

fixes more CosmosDB tests, which were not caught by the previous PR #1315 

## Why it does that

_Briefly state why the change was necessary._

## Further notes

There seems to be a functional difference between the Cosmos Emulator (which I used for testing locally) and the actual CosmosDB instance: when sorting based on a non-existing field, the cosmos emulator returns an empty list, whereas on the "real" cosmos does not affect the result.

## Linked Issue(s)

Closes #1313

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [x] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java [hunk 1]
```diff
@@ -420,7 +420,7 @@ void findAll_verifyFiltering_invalidFilterExpression() {
 
         var query = QuerySpec.Builder.newInstance().filter("something contains other").build();
 
-        assertThatThrownBy(() -> store.queryNegotiations(query)).isInstanceOfAny(IllegalArgumentException.class).hasMessage("Cannot build SqlParameter for operator: contains");
+        assertThatThrownBy(() -> store.queryNegotiations(query)).isInstanceOfAny(IllegalArgumentException.class).hasMessage("Cannot build WHERE clause, reason: unsupported operator contains");
```
Comment (ndr-brt) [inline extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java:423]: In general I would avoid testing exception messages, especially in integration tests

Comment (algattik) [reply extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java:423]: Well to me it seems a good idea, so we ensure the exception we are testing for is not masked by an unrelated one

**Review by algattik — APPROVED** [review]

File: extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java (hunk 1 above)
Comment (paullatzelsperger) [reply extensions/azure/cosmos/contract-negotiation-store-cosmos/src/test/java/org/eclipse/dataspaceconnector/contract/negotiation/store/CosmosContractNegotiationStoreIntegrationTest.java:423]: I tend to agree with @algattik, and asserting exception message has already surfaced problems for me on several occasions. I like tests to be as rigid as possible - you can never be too certain :)

**Review by ndr-brt — APPROVED** [review]
