### PR TITLE
Management-api: Create DTO entities and controller Classes

### LINKED ISSUE #587: DataManagementApi: Create API for Asset and DataAddress
## API Endpoints
- `POST /api/v1/assets`: creates a new Asset, `AssetEntryDto` must be passed in body. Returns `void`
- `GET /api/v1/assets`: gets all assets, accepts paging spec, returns `List<AssetDto>`
- `GET /api/v1/assets/{id}`: gets one particular asset as `AssetDto`, returns `AssetDto`
- `DELETE /api/v1/assets/{id}`: delete an asset. should throw an `IllegalStateException` if not possible. Returns `void`.

## DTOs
```java
public class AssetEntryDto {
  private AssetDto asset;
  private DataAddressDto dataAddress;
  //getters, setters, etc.
}

public class AssetDto {
  private Map<String, Object> properties;
  //getters, setters, etc.
}

public class DataAddress {
  private Map<String, Object> properties;
  //getters, setters, etc.
}
```

### PR DESCRIPTION
**Pull request by diegogomez-zf**
closes #587

### CODE REVIEW

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddress.java [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    private DataAddress(){
+    }
+
+    public Map<String, Object> getProperties() {
+        return properties;
+    }
+
+    public void setProperties(Map<String, Object> properties) {
+        this.properties = properties;
+    }
```
Comment (florianrusch-cluetec) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddress.java:23]: I discussed this topic already with @paullatzelsperger here: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/641/files/fa66170632c2af2761d69bfc2499744d9125ee1f#r802525767
We don't need any public setter in the model classes
```suggestion
```

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+    }
+
+    public AssetDto getAssetDto() {
+        return assetDto;
+    }
+
+    public void setAssetDto(AssetDto assetDto) {
+        this.assetDto = assetDto;
+    }
+
```
Comment (florianrusch-cluetec) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java:23]: See the commentary below in this file:
```suggestion
```

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+    public DataAddress getDataAddress() {
+        return dataAddress;
+    }
+
+    public void setDataAddress(DataAddress dataAddress) {
+        this.dataAddress = dataAddress;
+    }
```
Comment (florianrusch-cluetec) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java:30]: See the commentary below in this file
```suggestion
```

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDto.java [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+    private AssetDto() {
+    }
+
+    public Map<String, Object> getProperties() {
+        return properties;
+    }
+
+    public void setProperties(Map<String, Object> properties) {
+        this.properties = properties;
+    }
```
Comment (florianrusch-cluetec) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDto.java:23]: See the commentary below in the other files
```suggestion
```

**Review by florianrusch-cluetec — CHANGES_REQUESTED** [review]
Good first draft :-)

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 5]
```diff
@@ -0,0 +1,71 @@
...
+        //Todo: implement
+    }
+
+    @Test
+    void createAssetAlreadyExists(){
+        //Todo: implement
+    }
+
+    @Test
+    void createAssetPathNotExists(){
```
Comment (florianrusch) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:42]: What do you mean with path not exists?

**Review by florianrusch — CHANGES_REQUESTED** [review]

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDto.java [hunk 6]
```diff
@@ -0,0 +1,58 @@
...
+package org.eclipse.dataspaceconnector.api.datamanagement.asset.model;
+
+import java.util.Map;
+
+import com.fasterxml.jackson.annotation.JsonCreator;
+import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
+import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
+
+@JsonDeserialize(builder = AssetDto.Builder.class)
+public class AssetDto {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDto.java:23]: lots of unneeded newlines in this file.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDto.java [hunk 7]
```diff
@@ -0,0 +1,58 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDto.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java [hunk 8]
```diff
@@ -0,0 +1,66 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java:2]: As far as I know the Copyright should go to ZF.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+        return dataAddress;
+    }
+
+    @JsonPOJOBuilder(withPrefix = "")
+    public static final class Builder {
+
+        private final AssetEntryDto assetEntryDto;
+
+        private Builder() {
+
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDto.java:43]: redundant newline

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddress.java [hunk 10]
```diff
@@ -0,0 +1,58 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddress.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java [hunk 11]
```diff
@@ -0,0 +1,87 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddress.java [hunk 12]
```diff
@@ -0,0 +1,58 @@
...
+package org.eclipse.dataspaceconnector.api.datamanagement.asset.model;
+
+import java.util.Map;
+
+import com.fasterxml.jackson.annotation.JsonCreator;
+import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
+import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
+
+@JsonDeserialize(builder = DataAddress.Builder.class)
+public class DataAddress {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddress.java:23]: Please rename to `*Dto`. Sorry, overlooked this in the issue spec, which I'll update.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java [hunk 13]
```diff
@@ -0,0 +1,87 @@
...
+public class AssetController {
+
+    private final Monitor monitor;
+
+    public AssetController(Monitor monitor) {
+        this.monitor = monitor;
+    }
+
+    @POST
+    @Path("")
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java:48]: can be deleted

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java [hunk 14]
```diff
@@ -0,0 +1,87 @@
...
+    public void createAsset(AssetEntryDto assetEntryDto) {
+        monitor.debug(format("Asset created %s", assetEntryDto.getAssetDto()));
+    }
+
+    @GET
+    @Path("")
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java:54]: can be deleted

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerServiceExtension.java [hunk 15]
```diff
@@ -0,0 +1,38 @@
...
+
+    @Override
+    public String name() {
+        return "EDC Control API";
+    }
+
+    @Override
+    public void initialize(ServiceExtensionContext serviceExtensionContext) {
+        monitor = serviceExtensionContext.getMonitor();
+        webService.registerController(new AssetController(monitor));
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerServiceExtension.java:36]: As we will use a custom jetty context, please replace with:
```java
//avoid jetty throwing exceptions down the road
if (!context.getConfig().hasKey("web.http.data.port")) {
    monitor.severe("No port mapping entry for context 'data' ('web.http.data.port=...') found in configuration. The Data Management API will not be available!");
} else {
    // todo: also register the Authorization filter, once https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/598 is finished:
        // webService.registerResource("data", new AuthorizationRequestFilter());
       webService.registerResource("data", new AssetController(monitor));
}
```

File: extensions/api/data-management/asset/build.gradle.kts [hunk 16]
```diff
@@ -0,0 +1,51 @@
...
+    testImplementation("io.rest-assured:rest-assured:4.4.0")
+
+    testImplementation(project(":extensions:in-memory:negotiation-store-memory"))
+    testImplementation(testFixtures(project(":common:util")))
+
+}
+
+publishing {
+    publications {
+        create<MavenPublication>("AssetDTO-api") {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/build.gradle.kts:46]: lowercase: should be `asset-api`

File: extensions/api/data-management/asset/build.gradle.kts [hunk 17]
```diff
@@ -0,0 +1,51 @@
...
+}
+
+dependencies {
+    api(project(":spi"))
+    api(project(":common:util"))
+    api(project(":extensions:http"))
+
+    implementation("jakarta.ws.rs:jakarta.ws.rs-api:${rsApi}")
+
+    testImplementation(project(":core:"))
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/build.gradle.kts:29]: replace all `testImplementations` with this:
```kotlin
    testImplementation(testFixtures(project(":common:util")))
    testImplementation("com.squareup.okhttp3:okhttp:${okHttpVersion}")
```

File: extensions/api/data-management/asset/build.gradle.kts [hunk 18]
```diff
@@ -0,0 +1,51 @@
...
+val infoModelVersion: String by project
+val rsApi: String by project
+val jerseyVersion: String by project
+
+plugins {
+    `java-library`
+}
+
+dependencies {
+    api(project(":spi"))
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/build.gradle.kts:23]: here, `:spi:core-spi` is sufficient

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerServiceExtension.java [hunk 19]
```diff
@@ -0,0 +1,38 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerServiceExtension.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension [hunk 20]
```diff
@@ -0,0 +1,15 @@
+#
+#  Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/resources/META-INF/services/org.eclipse.dataspaceconnector.spi.system.ServiceExtension:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDtoTest.java [hunk 21]
```diff
@@ -0,0 +1,45 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetDtoTest.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDtoTest.java [hunk 22]
```diff
@@ -0,0 +1,49 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/AssetEntryDtoTest.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddressTest.java [hunk 23]
```diff
@@ -0,0 +1,45 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/model/DataAddressTest.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/test/java/AssetControllerIntegrationTest.java [hunk 24]
```diff
@@ -0,0 +1,173 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerIntegrationTest.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/test/java/AssetControllerIntegrationTest.java [hunk 25]
```diff
@@ -0,0 +1,173 @@
...
+ * This program and the accompanying materials are made available under the
+ * terms of the Apache License, Version 2.0 which is available at
+ * https://www.apache.org/licenses/LICENSE-2.0
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ *
+ * Contributors:
+ *   Diego Gomez - Initial API and Implementation
+ */
+
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerIntegrationTest.java:13]: Missing package declaration

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 26]
```diff
@@ -0,0 +1,66 @@
+/*
+ * Copyright (c) 2022 Diego Gomez
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:2]: As far as I know the Copyright should go to ZF, at least that is my latest information.

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 27]
```diff
@@ -0,0 +1,66 @@
...
+ * This program and the accompanying materials are made available under the
+ * terms of the Apache License, Version 2.0 which is available at
+ * https://www.apache.org/licenses/LICENSE-2.0
+ *
+ * SPDX-License-Identifier: Apache-2.0
+ *
+ * Contributors:
+ *   Diego Gomez - Initial API and Implementation
+ */
+
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:13]: Missing package declaration.

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 28]
```diff
@@ -0,0 +1,66 @@
...
+        //Todo: implement
+    }
+
+    @Test
+    void getAssetFromID() {
+        //Todo: implement
+    }
+
+    @Test
+    void getAssetFromIDNotExists() {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:52]: rename `getAssetById_notExists`

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 29]
```diff
@@ -0,0 +1,66 @@
...
+        //Todo: implement
+    }
+
+    @Test
+    void listAllAssets() {
+        //Todo: implement
+    }
+
+    @Test
+    void getAssetFromID() {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:47]: rename `getAssetById`

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 30]
```diff
@@ -0,0 +1,66 @@
...
+        //Todo: implement
+    }
+
+    @Test
+    void createAssetAlreadyExists() {
+        //Todo: implement
+    }
+
+    @Test
+    void listAllAssets() {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:42]: rename `getAllAssets`

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 31]
```diff
@@ -0,0 +1,66 @@
...
+        //Todo: implement
+    }
+
+    @Test
+    void getAssetFromIDNotExists() {
+        //Todo: implement
+    }
+
+    @Test
+    void removeAssetfromID() {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:57]: rename `deleteAsset`

File: extensions/api/data-management/asset/src/test/java/AssetControllerTest.java [hunk 32]
```diff
@@ -0,0 +1,66 @@
...
+        //Todo: implement
+    }
+
+    @Test
+    void removeAssetFromIDNotExists() {
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/AssetControllerTest.java:62]: rename `deleteAsset_notExists`

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
Normally I am hesitant to review draft PRs, but since M2 is fast approaching I did. 
We really need to sort out the Copyright issue. In case ZF really actually relinquishes its copyright, we need to clarify with the EF whether individual contributors can hold Copyright.

**Review by jimmarino — CHANGES_REQUESTED** [review]
We need to sort out the Copyright ASAP. If this is assigned to ZF, we should have recorded acknowledgment as part of this PR.

File: extensions/api/data-management/asset/build.gradle.kts (hunk 18 above)
Comment (diegogomez-cluetec) [reply extensions/api/data-management/asset/build.gradle.kts:23]: I had to import also :spi:web-spi" for the WebService instance in in the method initialize() from the class AssetControllerServiceExtension (line 36) since it's not part of core-spi (at least from the current version)

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java [hunk 33]
```diff
@@ -0,0 +1,85 @@
...
+import org.eclipse.dataspaceconnector.spi.monitor.Monitor;
+import org.eclipse.dataspaceconnector.spi.query.QuerySpec;
+import org.eclipse.dataspaceconnector.spi.query.SortOrder;
+
+import java.util.Collections;
+import java.util.List;
+
+import static java.lang.String.format;
+
+@Consumes({ MediaType.APPLICATION_JSON })
```
Comment (MoritzKeppler) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java:36]: Propose to use OpenAPI / swagger annotations to document more details about the endpoints, see https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
@paullatzelsperger @jimmarino  do you agree?

**Review by jimmarino — COMMENTED** [review]
Thanks for resolving the copyright issue.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java (hunk 33 above)
Comment (jimmarino) [reply extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java:36]: > Propose to use OpenAPI / swagger annotations to document more details about the endpoints, see https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations @paullatzelsperger @jimmarino do you agree?

Sounds like a great idea. I also like @paullatzelsperger 's suggestion to use interfaces.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerServiceExtension.java [hunk 34]
```diff
@@ -0,0 +1,44 @@
...
+import org.eclipse.dataspaceconnector.spi.system.ServiceExtensionContext;
+
+public class AssetControllerServiceExtension implements ServiceExtension {
+
+    @Inject
+    private WebService webService;
+
+    @Override
+    public String name() {
+        return "EDC Control API";
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerServiceExtension.java:29]: Please remove the `name()` override

File: extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerIntegrationTest.java [hunk 35]
```diff
@@ -0,0 +1,170 @@
...
+import java.io.IOException;
+import java.util.Collections;
+
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.mockito.Mockito.mock;
+
+public class AssetControllerIntegrationTest {
+
+    private static int port;
+    ObjectMapper objectMapper;
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerIntegrationTest.java:47]: can be `private`

File: extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerIntegrationTest.java [hunk 36]
```diff
@@ -0,0 +1,170 @@
...
+    void getSingleAsset_notFound() throws IOException {
+        var id = "test-id";
+        try (var response = get(basePath() + "/" + id)) {
+            //assertThat(response.code()).isEqualTo(400);
+        }
+    }
+
+    @Test
+    void postAsset() throws IOException {
+        var assetDto = AssetDto.Builder.newInstance().properties(Collections.singletonMap("Asset-1", "An Asset")).build();
```
Comment (paullatzelsperger) [inline extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetControllerIntegrationTest.java:95]: may want to extract a method `createAssetDto()` and `createDataAddressDto()` either directly in the test, or - even better - `static` in a `TestFunctions` class

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java (hunk 33 above)
Comment (florianrusch-zf) [reply extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java:36]: I would suggest moving this to a separate topic/PR where we can introduce these interfaces and make use of them in all existing api controllers. We should try to complete this PR asap to finally have a first draft of the openapi spec for the management part.

Comment (paullatzelsperger) [reply extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/AssetController.java:36]: there is also issue #645 where we could add this as a task

**Review by paullatzelsperger — APPROVED** [review]

**Review by jimmarino — APPROVED** [review]
