### PR TITLE
Fix: do not use `QuerySpec` when SqlContractDefinitionStore#findAll()

### LINKED ISSUE #1515: SQL:  Connector sends out 50 contract offers max.
# Bug Report

## Describe the Bug

When a connector requests a catalog from another connector, it only gets the first 50 contract offers, even if the connector would be able to send out a lot more offers.

### Expected Behavior
- all contract offers can be accessed by another connector

### Observed Behavior
- another connector can only access the first 50 contract offers

## Steps to Reproduce
1. Setup Connector with SQL persistence
2. Setup the data so that the connector would generate more than 50 offers
3. Request catalog with another connector
  -> catalog contains only 50 offers 

## Context Information

- Requires SQL Extensions on offer provider side

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

Does not use a `QuerySpec` when executing `SqlContractDefinitionStore#findAll`, instead execute a plain `SELECT * FROM...`.

## Why it does that

all = no limits!

## Linked Issue(s)

Closes #1515 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java [hunk 1]
```diff
@@ -69,7 +69,15 @@ ContractDefinition mapResultSet(ResultSet resultSet) throws Exception {
 
     @Override
     public @NotNull Collection<ContractDefinition> findAll() {
-        return findAll(QuerySpec.none()).collect(Collectors.toList());
+        return transactionContext.execute(() -> {
```
Comment (ndr-brt) [inline extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java:72]: I would make this more explicit as it was done in the `SqlAssetIndex` at line 132, passing to the other `findAll` method a `QuerySpec` instance with an insanely high `limit` value.
In this way the thing will be explicit (as I would expect this to change in the future), there will be no duplication and no SQL syntax will overflow in the store implementation

Comment (paullatzelsperger) [reply extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java:72]: There isn't really any duplication, there is just two (slightly) different SQL statements. In reality those two approaches would have the same effect, and once we have true pagination in IDS, we can remove the parameterless `findAll()` method completely.

What do you mean by "SQL syntax overflow"?

Comment (ndr-brt) [reply extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java:72]: having a string with `SELECT something FROM somewhere` in the `Store`/`Index`, we never did that anywhere else, all the SQL stuff is in the `Statements` class

Comment (paullatzelsperger) [reply extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java:72]: ah got it. How about we remove `findAll()` altogether then, and provide a static method `QuerySpec.max()` that creates a QuerySpec with `limit = Integer.MAX_VALUE`?

Comment (paullatzelsperger) [reply extensions/sql/contract-definition-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/contractdefinition/store/SqlContractDefinitionStore.java]: [this commit](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/1539/commits/a73fa531f3b37a7175912eb5d1f1898514a3dc7b) removes the parameterless `findAll()`. WDYT?

**Review by ronjaquensel — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]
Totally agree on `findAll()`'s inline. Good for me then
