### PR TITLE
fix(ContractOffer): add asset not null check when building a ContractOffer

### LINKED ISSUE #2052: `ContractOffer.asset` should be a required field (not null)
# Bug Report

## Describe the Bug
With `ContractOffer.Builder` is possible to build a `ContractOffer` with a null asset field. 
But this violate the `@NotNull` annotation on the getter

```java
@NotNull
public Asset getAsset() {
     return asset;
}
```

### Expected Behavior

It should throw an exception if the field is null

### Observed Behavior

This is valid:

```java
 ContractOffer.Builder.newInstance().id("some-id")
     .policy(Policy.Builder.newInstance().build())
     .build()
```

## Possible Implementation

Add a validation check on `ContractOffer.Builder#build` on asset being null

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

Adds the check on asset field when building a ContractOffer

## Why it does that

For consistency with the `getAsset` API, since the Asset is mandatory in the `ContractOffer`

## Further notes

While fixing this the style of the `ContractOffer.Builder` has been changed following our usual builder pattern

## Linked Issue(s)

Closes #2052 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java [hunk 1]
```diff
@@ -202,6 +202,10 @@ public Builder policy(Policy policy) {
         public ContractOffer build() {
             Objects.requireNonNull(id);
 
+            if (asset == null) {
```
Comment (paullatzelsperger) [inline spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java:205]: an alternative would be `Objects.requireNonNull(asset, "Asset must not be null")`, which would throw a NPE, but it would make the code a bit more readable, and we have it in many other places in the code base as well.

File: data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java [hunk 2]
```diff
@@ -145,7 +145,11 @@ void testSendArtifactRequestMessage(RemoteMessageDispatcherRegistry dispatcher)
 
     @Test
     void testSendContractOfferMessage(RemoteMessageDispatcherRegistry dispatcher) {
-        var contractOffer = ContractOffer.Builder.newInstance().id("id").policy(Policy.Builder.newInstance().build()).build();
+        var contractOffer = ContractOffer.Builder.newInstance()
```
Comment (paullatzelsperger) [inline data-protocols/ids/ids-api-multipart-dispatcher-v1/src/test/java/org/eclipse/dataspaceconnector/ids/api/multipart/client/MultipartDispatcherIntegrationTest.java:148]: minor nit: building the offer could be moved to a separate method, to avoid code duplication. We often create two methods, one returning the object itself, when just a generic default is needed, and another one, returning the `Builder`, so that we can easily customize the object.

**Review by paullatzelsperger — COMMENTED** [review]
minor remarks directly in code.

File: spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java (hunk 1 above)
Comment (wolf4ood) [reply spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java]: Since i'm here should i change also the policy check?

Comment (paullatzelsperger) [reply spi/control-plane/contract-spi/src/main/java/org/eclipse/dataspaceconnector/spi/types/domain/contract/offer/ContractOffer.java]: yes pls :)

**Review by paullatzelsperger — APPROVED** [review]
