### PR TITLE
Fix Sample 5, closes #381

### LINKED ISSUE #381: Sample 05-file-transfer-cloud broken (assetId)
When running sample 05 according to its instructions, the consumer log contains:
```
SEVERE 2021-12-08T10:02:01.741348 Error caught in transfer process manager
java.lang.NullPointerException
	at java.base/java.net.URI$Parser.parse(URI.java:3104)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	at org.eclipse.dataspaceconnector.ids.core.message.DataRequestMessageSender.send(DataRequestMessageSender.java:92)
	at org.eclipse.dataspaceconnector.ids.core.message.DataRequestMessageSender.send(DataRequestMessageSender.java:44)
	at org.eclipse.dataspaceconnector.ids.core.message.IdsRemoteMessageDispatcher.send(IdsRemoteMessageDispatcher.java:46)
	at org.eclipse.dataspaceconnector.transfer.core.protocol.provider.RemoteMessageDispatcherRegistryImpl.send(RemoteMessageDispatcherRegistryImpl.java:47)
	at org.eclipse.dataspaceconnector.transfer.core.transfer.TransferProcessManagerImpl.sendOrProcessProvisionedRequests(TransferProcessManagerImpl.java:294)
	at org.eclipse.dataspaceconnector.transfer.core.transfer.TransferProcessManagerImpl.run(TransferProcessManagerImpl.java:116)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Presumably the cause is a missing assetId in the query

### PR DESCRIPTION
**Pull request by DominikPinsel**
Signed-off-by: Dominik Pinsel <dominik.pinsel@daimler.com>

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### CODE REVIEW

File: core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java [hunk 1]
```diff
@@ -294,12 +294,14 @@ private int sendOrProcessProvisionedRequests() {
                 dispatcherRegistry.send(Void.class, dataRequest, process::getId);
             } else {
                 var response = dataFlowManager.initiate(dataRequest);
-                if (ResponseStatus.ERROR_RETRY == response.getFailure().status()) {
+                if (response.getFailure() != null &&
```
Comment (ndr-brt) [inline core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java:297]: the `failed()` method is more easy to read.

File: samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java [hunk 2]
```diff
@@ -30,7 +30,8 @@ public String name() {
     public void initialize(ServiceExtensionContext context) {
         var dataFlowMgr = context.getService(DataFlowManager.class);
         var dataAddressResolver = context.getService(DataAddressResolver.class);
-        var blobStoreApi = context.getService(BlobStoreApi.class);
```
Comment (ndr-brt) [inline samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java:33]: Why not using the BlobStoreApi instance already registered?

Comment (DominikPinsel) [reply samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java:33]: The extension, that implements the BlobStoreApiImpl class, is an library and does not register it in the service context. Maybe this was different in the past.

File: core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java (hunk 1 above)
Comment (DominikPinsel) [reply core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java:297]: If this is ok for you I'd leave it like this. I just added a null check here and cannot tell, why the status is compared to ERROR_RETRY instead of calling the failed() method.

File: samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java (hunk 2 above)
Comment (ndr-brt) [reply samples/05-file-transfer-cloud/transfer-file/src/main/java/org/eclipse/dataspaceconnector/extensions/transfer/CloudTransferExtension.java:33]: Yes, sorry, it gets registered in the `blob-provision` module, that's not included here.

File: core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java (hunk 1 above)
Comment (ndr-brt) [reply core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java:297]: Probably it was my fault, the way to test if a result is failed is to call the `failed` method. Since the result is failed, the failure is not null, so I would prefer that over the null checking

Comment (ndr-brt) [reply core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java:297]: yes

Comment (DominikPinsel) [reply core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java]: @ndr-brt done :)

**Comment by DominikPinsel** [comment]
Updated the sample 5 multipart documentation

**Comment by MoritzKeppler** [comment]
@paullatzelsperger fine for you?

**Review by MoritzKeppler — APPROVED** [review]
