### PR TITLE
DPF Azure storage: Write ".complete" blob

### LINKED ISSUE #1210: DPF: Blob storage transfer: missing .complete blob
# Bug Report

## Describe the Bug

When a data transfer target is an Azure Storage container, the consumer does not detect transfer completion. 

## Detailed Description

`ObjectContainerStatusChecker` polls for a blob called `*.complete` in the destination storage container to determine if a transfer has completed on the provider side. As `AzureStorageDataSink` does not currently write this file, transfer completion is never detected.

## Possible Implementation

Write a blob named e.g. `.complete` in `AzureStorageDataSink` after all parts were transferred.

### PR DESCRIPTION
**Pull request by algattik**
## What this PR changes/adds

AzureStorageDataSink writes a blob named `.complete` after all parts are transferred

## Why it does that

End-to-end flow for blob storage transfers across EDC and DPF is not working (#1183). This is one of multiple PRs to solve several issues causing the problem.

When a data transfer target is an Azure Storage container, the consumer did not detect transfer completion. 

`ObjectContainerStatusChecker` polls for a blob called `*.complete` in the destination storage container to determine if a transfer has completed on the provider side. As `AzureStorageDataSink` did not currently write this file, transfer completion was never detected.

## Linked Issue(s)

Closes #1210 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSink.java [hunk 1]
```diff
@@ -59,6 +59,10 @@ public CompletableFuture<StatusResult<Void>> transfer(DataSource source) {
 
     protected abstract StatusResult<Void> transferParts(List<DataSource.Part> parts);
 
+    protected StatusResult<Void> complete() {
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSink.java:62]: It deserves some docs

File: extensions/data-plane/data-plane-spi/src/test/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSinkTest.java [hunk 2]
```diff
@@ -41,6 +41,9 @@ class ParallelSinkTest {
     String dataSourceName = faker.lorem().word();
     String dataSourceContent = faker.lorem().characters();
     String errorMessage = faker.lorem().sentence();
+    InputStreamDataSource dataSource = new InputStreamDataSource(
```
Comment (ndr-brt) [inline extensions/data-plane/data-plane-spi/src/test/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSinkTest.java:44]: There are two tests that instantiate the same object as this, please use this everywhere or local instances everywhere (I'm more for the latter, but no strong opinion on it)

Comment (ndr-brt) [inline extensions/data-plane/data-plane-spi/src/test/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSinkTest.java:44]: There are two tests that instantiate the same object as this, please use this everywhere or local instances everywhere (I'm more for the latter, but no strong opinion on it)

Comment (algattik) [reply extensions/data-plane/data-plane-spi/src/test/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSinkTest.java:44]: Good catch, fixed

File: extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSink.java (hunk 1 above)
Comment (algattik) [reply extensions/data-plane/data-plane-spi/src/main/java/org/eclipse/dataspaceconnector/dataplane/spi/pipeline/ParallelSink.java:69]: Added javadoc

**Review by ndr-brt — APPROVED** [review]

**Review by bscholtes1A — APPROVED** [review]

**Review by paullatzelsperger — APPROVED** [review]
