### PR TITLE
test: fix failure of TransferProcessEventDispatchTest (fixes #1616)

### LINKED ISSUE #1616: test: fix failure of TransferProcessEventDispatchTest
# Bug Report

## Describe the Bug
3 test cases of TransferProcessEventDispatchTest fail.

### Expected Behavior
The tests pass.

## Steps to Reproduce

```
$ ./gradlew extensions:api:data-management:transferprocess:test
```

## Context Information
_Add any other context about the problem here._

- Used version: main (abc8912ebb54c42bb4e5f67c4e05504c0ef46691)
- OS: Ubuntu 22.04
- JDK: openjdk-11-jdk (11.0.15+10-Ubuntu-0ubuntu0.22.04.1)

## Detailed Description

```
TransferProcessEventDispatchTest > shouldDispatchEventsOnTransferProcessStateChanges(TransferProcessService, EventRouter, RemoteMessageDispatcherRegistry) FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest 
    Wanted but not invoked:
    eventSubscriber.on(
        isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessInitialized)
    );
    -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventsOnTransferProcessStateChanges$0(TransferProcessEventDispatchTest.java:73)
    Actually, there were zero interactions with this mock.
     within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.shouldDispatchEventsOnTransferProcessStateChanges(TransferProcessEventDispatchTest.java:72)

        Caused by:
        Wanted but not invoked:
        eventSubscriber.on(
            isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessInitialized)
        );
        -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventsOnTransferProcessStateChanges$0(TransferProcessEventDispatchTest.java:73)
        Actually, there were zero interactions with this mock.
            at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventsOnTransferProcessStateChanges$0(TransferProcessEventDispatchTest.java:73)

TransferProcessEventDispatchTest > shouldDispatchEventOnTransferProcessFailure(TransferProcessService, EventRouter, RemoteMessageDispatcherRegistry) FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest 
    Wanted but not invoked:
    eventSubscriber.on(
        isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessFailed)
    );
    -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessFailure$3(TransferProcessEventDispatchTest.java:126)
    Actually, there were zero interactions with this mock.
     within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.shouldDispatchEventOnTransferProcessFailure(TransferProcessEventDispatchTest.java:126)

        Caused by:
        Wanted but not invoked:
        eventSubscriber.on(
            isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessFailed)
        );
        -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessFailure$3(TransferProcessEventDispatchTest.java:126)
        Actually, there were zero interactions with this mock.
            at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessFailure$3(TransferProcessEventDispatchTest.java:126)

TransferProcessEventDispatchTest > shouldDispatchEventOnTransferProcessCanceled(TransferProcessService, EventRouter, RemoteMessageDispatcherRegistry) FAILED
    org.awaitility.core.ConditionTimeoutException: Assertion condition defined as a lambda expression in org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest 
    Wanted but not invoked:
    eventSubscriber.on(
        isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessCancelled)
    );
    -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessCanceled$2(TransferProcessEventDispatchTest.java:106)
    Actually, there were zero interactions with this mock.
     within 10 seconds.
        at app//org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:164)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:119)
        at app//org.awaitility.core.AssertionCondition.await(AssertionCondition.java:31)
        at app//org.awaitility.core.ConditionFactory.until(ConditionFactory.java:939)
        at app//org.awaitility.core.ConditionFactory.untilAsserted(ConditionFactory.java:723)
        at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.shouldDispatchEventOnTransferProcessCanceled(TransferProcessEventDispatchTest.java:106)

        Caused by:
        Wanted but not invoked:
        eventSubscriber.on(
            isA(org.eclipse.dataspaceconnector.spi.event.transferprocess.TransferProcessCancelled)
        );
        -> at org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessCanceled$2(TransferProcessEventDispatchTest.java:106)
        Actually, there were zero interactions with this mock.
            at app//org.eclipse.dataspaceconnector.api.datamanagement.transferprocess.service.TransferProcessEventDispatchTest.lambda$shouldDispatchEventOnTransferProcessCanceled$2(TransferProcessEventDispatchTest.java:106)
```

## Possible Implementation

* Setting retly.limit to higher values enables transition to expected state.
* Disabling exponential make transition to expected failure state within 10 seconds (which is default timeout of Awaitility).

in TransferProcessEventDispatchTest setUp:

```
        extension.setConfiguration(Map.of("edc.transfer.send.retry.limit", "5",
                                          "edc.transfer.send.retry.base-delay.ms", "0"));
        extension.registerServiceMock(TransferWaitStrategy.class, () -> 1);
```

### PR DESCRIPTION
**Pull request by iwasakims**
## What this PR changes/adds

* Setting retly.limit to higer values enables transision to expected state.
* Disabling exponentional make transition to expected failure state within 10 seconds (which is default timeout of Awaitility).
* Waiting completion of EventRouter tasks.

## Linked Issue(s)

Closes #1616

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [n/a] documented public classes/methods?
- [n/a] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

**Review by ndr-brt — CHANGES_REQUESTED** [review]
Thank you for pointing the issue and provide a solution, anyway the only needed modification is to register a mocked `TransferWaitStrategy` at a very low value:
```java
extension.registerServiceMock(TransferWaitStrategy.class, () -> 1);
```
I already noticed this and the fix was provided also by #1609 

The other modifications are not needed, especially the `ForkJoinPool` thing seems completely out of context.
Please adapt the PR to get it approved & merged, otherwise we'll wait for #1609 to be merged

**Comment by ndr-brt** [comment]
> > anyway the only needed modification is to register a mocked TransferWaitStrategy at a very low value:
> 
> Changing only TransferWaitStrategy did not worked. @ndr-brt.

You get the same error? To me it worked.

**Comment by iwasakims** [comment]
> You get the same error?

Yes.

> The other modifications are not needed, especially the ForkJoinPool thing seems completely out of context.

CompletableFuture#runAsync used in EventRouterImpl depends on the common pool. There is no other reliable way to make the task finish since the returned futures are not exposed.
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/0f17aee8eb46c6ba608ac84e5e24570731a4edbd/core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventRouterImpl.java#L45

Injecting our own Executor and using it could be an option to make it controllable (fot testing).

**Comment by ndr-brt** [comment]
The use of an injected `ExecutorService` was intended to be done, not for testing purposes but to have the pool independent and configurable, this could mashes two potatoes with one fork.
Could you adapt this PR to use a dedicated fixed thread executor defined into the `EventRouter`? This will solve the issue, then I will provide an issue to make the pool size configurable as well.

**Comment by iwasakims** [comment]
@ndr-brt I updated and rebased the PR based on your suggestion. I can see the test pass quite faster than before.

**Review by ndr-brt — APPROVED** [review]
Good to go, I think we need a standard about how to inject and configure executor services, but we will discuss this later on

File: core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventExecutorServiceContainer.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+package org.eclipse.dataspaceconnector.core.event;
+
+import org.jetbrains.annotations.NotNull;
+
+import java.util.concurrent.ExecutorService;
+
+/**
+ * Holder class for a shared {@link ExecutorService} across event router implementations.
+ */
+public class EventExecutorServiceContainer {
```
Comment (paullatzelsperger) [inline core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventExecutorServiceContainer.java:24]: Why is this necessary? Why not register the `ExecutorService` directly?

File: core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java [hunk 2]
```diff
@@ -211,7 +213,10 @@ public OkHttpClient addHttpClient(ServiceExtensionContext context) {
 
     @Provider
     public EventRouter eventRouter(ServiceExtensionContext context) {
-        return new EventRouterImpl(context.getMonitor());
+        var executor = context.hasService(EventExecutorServiceContainer.class) ?
```
Comment (paullatzelsperger) [inline core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java:216]: This should be done with `@Provider(isDefault=true)` and `@Inject(required=false)`. That way, it would contribute the `ExecutorService` back to the `context`

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
generally I like the idea, I'd ask for just a few minor adaptations.

File: core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventExecutorServiceContainer.java (hunk 1 above)
Comment (ndr-brt) [reply core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventExecutorServiceContainer.java:24]: @paullatzelsperger I was wondering the same, then I saw that this pattern was already used by `DataTransferExecutorServiceContainer` in the `data-plane-spi` module.
Registering the `ExecutorService` directly would mean that there'll be only one `ExecutorService` registered and used by any extension, while I would prefer every context/extension to have the possibility to have their executor.
For this I would provide a standardize way to configure executors that would be used by different extensions, like keeping a `ExecutorServiceContexts` (or similar) that could be configured by every extension, in a way similar to the one we used in for the api subsystem.
Will open an issue with a proposal.

Comment (iwasakims) [reply core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventExecutorServiceContainer.java:24]: @paullatzelsperger I followed the existing convention for registering distinctive type for ExecutorService used by EventRouter as @ndr-brt mentioned.

Comment (paullatzelsperger) [reply core/base/src/main/java/org/eclipse/dataspaceconnector/core/event/EventExecutorServiceContainer.java:24]: @ndr-brt @iwasakims makes sense to me.

File: core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java (hunk 2 above)
Comment (paullatzelsperger) [reply core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java]: You're almost there. Please use `@Inject(required=false)`, so avoid an exception when no `EventExecutorServiceContainer` is registered.

Comment (iwasakims) [reply core/base/src/main/java/org/eclipse/dataspaceconnector/core/CoreServicesExtension.java]: I addressed your last comment. Thanks, @paullatzelsperger.

**Review by paullatzelsperger — APPROVED** [review]
