### PR TITLE
TransferProcessManager: Break lease after status check

### LINKED ISSUE #1206: TransferProcessManager: status checker does not rerun on each iteration
# Bug Report

## Describe the Bug

For consumer-side transfers that are `IN_PROGRESS`, a `StatusChecker` (when provided) should execute on every `TransferProcessManagerImpl` (every 5 seconds) to check if e.g. the destination blob has been produced.

Following refactoring of the lease mechanism (probably with changes in #724), when the `StatusChecker` reports that the transfer is not completed, the lease is not broken. Therefore the status checker is only run again at lease timeout (every 60 seconds).

### Expected Behavior
StatusChecker should execute every 5 seconds

### Observed Behavior
StatusChecker executes every 60 seconds

## Possible Implementation
Break lease explicitly as in `org.eclipse.dataspaceconnector.transfer.core.transfer.TransferProcessManagerImpl#processConsumerRequest`

### PR DESCRIPTION
**Pull request by algattik**
## What this PR changes/adds

For consumer-side transfers that are `IN_PROGRESS`, a `StatusChecker` (when provided) should execute on every `TransferProcessManagerImpl` (every 5 seconds) to check if e.g. the destination blob has been produced.

## Why it does that

Following refactoring of the lease mechanism (probably with changes in #724), when the `StatusChecker` reports that the transfer is not completed, the lease was not broken after a Status check resulting in the output being incomplete. Therefore the status checker was only run again at lease timeout (every 60 seconds).

## Linked Issue(s)

Closes #1206 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java [hunk 1]
```diff
@@ -633,6 +633,11 @@ private void updateTransferProcess(TransferProcess transferProcess, Consumer<Tra
         transferProcessStore.update(transferProcess);
     }
 
+    private void breakLease(TransferProcess process) {
+        // Break lease
```
Comment (ndr-brt) [inline core/transfer/src/main/java/org/eclipse/dataspaceconnector/transfer/core/transfer/TransferProcessManagerImpl.java:637]: this comments is not needed, the intent is already described by the method name

**Review by ndr-brt — APPROVED** [review]

**Review by paullatzelsperger — APPROVED** [review]
